### ISSUE TITLE
UI bug on Safari browser

### ISSUE THREAD

**Issue by miifan** [howznguyen/howz.dev#43]
On Safari browser, the images are not displaying clearly, also the layout is a bit messy. 
<img width="1440" alt="Screenshot 2023-04-14 at 11 43 15" src="https://user-images.githubusercontent.com/130728875/231943826-508aa37b-b29b-4e7c-842d-7b12283f3b1d.png">

**Comment by howznguyen** [comment]
@miifan 
Can you check safari version in you laptop and tell me for that ?

**Comment by namnh198** [comment]
> @miifan Can you check safari version in you laptop and tell me for that ?

Please provide more information (OS version, Safari Version,...). I tried version 16.4. It's okay for me

**Comment by miifan** [comment]
hi @namnh198 my Safari version is 16.2, MacOS: Ventura 13.1 
it's still happening at the moment when I retry.

**Comment by miifan** [comment]
<img width="1318" alt="Screenshot 2023-04-20 at 08 45 45" src="https://user-images.githubusercontent.com/130728875/233238191-852fe25b-7b6e-4d07-895d-0622aa264e0a.png">

**Comment by howznguyen** [comment]
I have fixed it and you can check again.
Thank you for contributing the bug.
